#!/bin/bash

git remote rm origin 
git remote add origin git@gitee.com:tiger7/tiger7.git
sleep 1
git branch --set-upstream-to=origin/master master

cd doc
git remote rm origin 
git remote add origin git@gitee.com:tiger7/doc.git
sleep 1
git branch --set-upstream-to=origin/master master


