#!/bin/bash

git remote rm origin 
git remote add origin git@github.com:skinos7/tiger7.git
git push origin master
git remote rm origin 
git remote add origin git@gitee.com:tiger7/tiger7.git
git pull
git branch --set-upstream-to=origin/master master

cd doc
git remote rm origin 
git remote add origin git@github.com:skinos7/doc.git
git push origin master
git remote rm origin 
git remote add origin git@gitee.com:tiger7/doc.git
git pull
git branch --set-upstream-to=origin/master master



