#!/bin/bash
TOPDIR=`pwd`

git status

# core project and tiger
if [ -d ${TOPDIR}/core ]; then
    cd ${TOPDIR}/core
    list=`ls`
    for tmp in $list
    do
        if [ -d ${TOPDIR}/core/${tmp} ]; then
            echo "status the ${tmp}"
            cd ${TOPDIR}/core/${tmp};git status
        fi
    done
fi
cd ${TOPDIR}

# Custom
for tmp in rice
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "status the ${tmp}"
        cd ${TOPDIR}/${tmp};git status
    fi
done

# MTK2 platform
for tmp in config/smtk2/
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "status the ${tmp}"
        cd ${TOPDIR}/${tmp};git status
    fi
done

# RK platform
for tmp in config/srkw/
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "status the ${tmp}"
        cd ${TOPDIR}/${tmp};git status
    fi
done

