#!/bin/bash
TOPDIR=`pwd`

git pull

# core project and mytry6
if [ -d ${TOPDIR}/core ]; then
    cd ${TOPDIR}/core
    list=`ls`
    for tmp in $list
    do
        if [ -d ${TOPDIR}/core/${tmp} ]; then
            echo "update the ${tmp}"
            cd ${TOPDIR}/core/${tmp};git pull
        fi
    done
fi
cd ${TOPDIR}

# Custom
for tmp in rice
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "update the ${tmp}"
        cd ${TOPDIR}/${tmp};git pull
    fi
done

# MTK platform
for tmp in smtk config/smtk/ smtk_boot
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "update the ${tmp}"
        cd ${TOPDIR}/${tmp};git pull
    fi
done

# MTK2 platform
for tmp in config/smtk2/
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "update the ${tmp}"
        cd ${TOPDIR}/${tmp};git pull
    fi
done

# WRT platform
for tmp in config/swrt/
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "update the ${tmp}"
        cd ${TOPDIR}/${tmp};git pull
    fi
done

