#!/bin/bash

###################################
############# D218 ################
###################################
make gBOARDID=smtk2-mt7628-d218-8m pid
make pidinfo
make clean
make distclean
make dep
make
make sz
make ftp
for tmp in h728 wlinker120
do
    make gBOARDID=smtk2-mt7628-d218-8m-${tmp} pid
    ./mkdel
    make dep
    make
    make sz
    make ftp
done

make gBOARDID=smtk2-mt7628-d218-std pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in wlinkr222 wlinkr320 wlinkr522 wlinker120 wlinkr200e ctcunion
do
    make gBOARDID=smtk2-mt7628-d218-std-${tmp} pid
    ./mkdel
    make dep
    make
    make sz
    make ftp
done

for tmp in oled ipsec uclibc sr sx ok gs gg ggnw xyc inrico zwzx jjsd hmjtx base rover wlinkr200e xexagon
do
    make gBOARDID=smtk2-mt7628-d218-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done



###################################
############# R600 ################
###################################
make gBOARDID=smtk2-mt7628-r600-std pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in wlinkr320 wlinkr522 ctcunion h728 xexagon giant
do
    make gBOARDID=smtk2-mt7628-r600-std-${tmp} pid
    ./mkdel
    make dep
    make
    make sz
    make ftp
done

for tmp in oled inrico wan
do
    make gBOARDID=smtk2-mt7628-r600-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done

make gBOARDID=swrt-mt7628-r600-std pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in wlinkr320 wlinkr522
do
    make gBOARDID=swrt-mt7628-r600-std-${tmp} pid
    ./mkdel
    make dep
    make
    make sz
    make ftp
done



###################################
############# D228 ################
###################################
make gBOARDID=smtk2-mt7621-d228-std pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in ff
do
    make gBOARDID=smtk2-mt7621-d228-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done



###################################
############# D228P ###############
###################################
make gBOARDID=smtk2-mt7621-d228p-std pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in hmjtx
do
    make gBOARDID=smtk2-mt7621-d228p-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done



###################################
############# V520 ################
###################################
make gBOARDID=smtk2-mt7621-v520 pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in greatwall donkey ddonkey zebra ltruck szsh udeer hifly
do
    make gBOARDID=smtk2-mt7621-v520-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done



###################################
############# V520B ###############
###################################
make gBOARDID=smtk2-mt7621-v520b pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in donkey ddonkey
do
    make gBOARDID=smtk2-mt7621-v520b-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done



###################################
############# H721 ################
###################################
make gBOARDID=smtk2-mt7621-h721 pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in waveshare
do
    make gBOARDID=smtk2-mt7621-h721-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done



###################################
############# H722 ################
###################################
make gBOARDID=smtk2-mt7621-h722 pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo

