#!/bin/bash

#for tmp in shost-x86-ubuntu shost-aarch64-ubuntu
#do
#    make gBOARDID=${tmp} pid
#    make test
#    make clean
#    make distclean
#    make dep
#    make
#    make repo
#done

for tmp in smtk2-mt7628-d218-h728 smtk2-mt7628-d218-8m smtk2-mt7628-d218-zwzx smtk2-mt7628-d218-sx smtk2-mt7628-d218-ok
do
    make gBOARDID=${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done
for tmp in smtk2-mt7628-d218
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
    make repo
done
for tmp in smtk2-mt7628-d218-std-wlinkr100  smtk2-mt7628-d218-std-wlinkr222  smtk2-mt7628-d218-std-wlinkr320
do
    make gBOARDID=${tmp} pid
    ./mkdel
    make test
    make dep
    make
    make sz
    make ftp
done



for tmp in smtk2-mt7621-d228
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
    make repo
done



for tmp in smtk2-mt7621-v520-greatwall smtk2-mt7621-v520-zebra smtk2-mt7621-v520-ddonkey smtk2-mt7621-v520-factory
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done
for tmp in smtk2-mt7621-v520
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
    make repo
done



for tmp in smtk2-mt7621-v520b-ddonkey
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done
for tmp in smtk2-mt7621-v520b
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
    make repo
done



for tmp in smtk2-mt7621-h721-factory
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done
for tmp in smtk2-mt7621-h721
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
    make repo
done

for tmp in smtk2-mt7621-h722
do
    make gBOARDID=${tmp} pid
    make test
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
    make repo
done

