
# **************************************** #
# ********* configure file defined******** #
# **************************************** #
gPROJECT_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/project.config" ]; \
	then echo ${gSCOPE_DIR}/project.config; \
	elif [ -f "${gCUSTOM_DIR}/project.config" ]; \
	then echo ${gCUSTOM_DIR}/project.config; \
	elif [ -f "${gHARDWARE_DIR}/project.config" ]; \
	then echo ${gHARDWARE_DIR}/project.config;\
	else echo ${gPLATFORM_DIR}/project.config;\
	fi)
gFARM_MKFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/farm.mk" ]; \
	then echo ${gSCOPE_DIR}/farm.mk; \
	elif [ -f "${gCUSTOM_DIR}/farm.mk" ]; \
	then echo ${gCUSTOM_DIR}/farm.mk; \
	elif [ -f "${gHARDWARE_DIR}/farm.mk" ]; \
	then echo ${gHARDWARE_DIR}/farm.mk;\
	else echo ${gPLATFORM_DIR}/farm.mk;\
	fi)
export gPROJECT_CFGFILE gFARM_MKFILE

# **************************************** #
# ********* compile environment ********** #
# **************************************** #
gARCH = x86
ARCH = $(gARCH)
LINUX_KARCH = $(ARCH)
export ARCH gARCH LINUX_KARCH
LN := ln -fs
CP := cp
FIND := find
INSTALL_BIN := install
INSTALL_DIR := install -d
export LN CP FIND INSTALL_BIN INSTALL_DIR
MAKE_VARS:=Nothing=NeedBeSet
export MAKE_VARS
# webpage thems
gpWUI_ADMIN_THEME = ace
export gpWUI_ADMIN_THEME
# misc cross environment
gLIB_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result
gLIB_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib
gCOM_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result
gCOM_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib -lland
gEXE_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result
gEXE_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib -lland -ldl
export gLIB_CFLAGS gLIB_LDFLAGS
export gCOM_CFLAGS gCOM_LDFLAGS
export gEXE_CFLAGS gEXE_LDFLAGS



