# **************************************** #
# ******* Directory Definition *********** #
# **************************************** #
# none

# **************************************** #
# ************ File Definition *********** #
# **************************************** #
gPROJECT_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/project.config" ]; \
	then echo ${gSCOPE_DIR}/project.config; \
	elif [ -f "${gCUSTOM_DIR}/project.config" ]; \
	then echo ${gCUSTOM_DIR}/project.config; \
	elif [ -f "${gHARDWARE_DIR}/project.config" ]; \
	then echo ${gHARDWARE_DIR}/project.config;\
	else echo ${gPLATFORM_DIR}/project.config;\
	fi)
gSKIN_MKFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/skin.mk" ]; \
	then echo ${gSCOPE_DIR}/skin.mk; \
	elif [ -f "${gCUSTOM_DIR}/skin.mk" ]; \
	then echo ${gCUSTOM_DIR}/skin.mk; \
	elif [ -f "${gHARDWARE_DIR}/skin.mk" ]; \
	then echo ${gHARDWARE_DIR}/skin.mk;\
	else echo ${gPLATFORM_DIR}/skin.mk;\
	fi)
export gPROJECT_CFGFILE gSKIN_MKFILE

# ********************************** #
# ******** Platform macro ********** #
# ********************************** #
gpSTORE_FILE = ${gHARDWARE}_${gCUSTOM}_${gSCOPE}.store
gpFIRMWARE_LOG = ${gHARDWARE}_${gCUSTOM}_${gSCOPE}.txt
gpFIRMWARE_FILE = ${gHARDWARE}_${gCUSTOM}_${gSCOPE}_${gVERSION}.tar.bz2
export gpSTORE_FILE gpFIRMWARE_LOG gpFIRMWARE_FILE

# **************************************** #
# ********* compile environment ********** #
# **************************************** #
gARCH = x86
ARCH = $(gARCH)
LINUX_KARCH = $(ARCH)
MAKE_VARS:=Nothing=NeedBeSet
export ARCH gARCH LINUX_KARCH MAKE_VARS
LN := ln -fs
CP := cp -fr
FIND := find
INSTALL_BIN := install
INSTALL_DIR := install -d
export LN CP FIND INSTALL_BIN INSTALL_DIR
# webpage thems
gpWUI_ADMIN_THEME = ace
export gpWUI_ADMIN_THEME
# misc cross environment
gLIB_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation
gLIB_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib  -levent
gCOM_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation
gCOM_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib -lland  -levent
gEXE_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation
gEXE_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib -lland -ldl  -levent
export gLIB_CFLAGS gLIB_LDFLAGS
export gCOM_CFLAGS gCOM_LDFLAGS
export gEXE_CFLAGS gEXE_LDFLAGS



