# **************************************** #
# ******* Directory Definition *********** #
# **************************************** #
# bootloader
gpBOOT_DIR := ${gPLATFORM_DIR}/boot
export gpBOOT_DIR

# **************************************** #
# ********* configure file defined******** #
# **************************************** #
# SDK的配置文件位置
gSDK_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/sdk.config" ]; \
	then echo ${gSCOPE_DIR}/sdk.config; \
	elif [ -f "${gCUSTOM_DIR}/sdk.config" ]; \
	then echo ${gCUSTOM_DIR}/sdk.config; \
	elif [ -f "${gHARDWARE_DIR}/sdk.config" ]; \
	then echo ${gHARDWARE_DIR}/sdk.config;\
	else echo ${gPLATFORM_DIR}/sdk.config;\
	fi)
gpBOOT_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/boot.config" ]; \
	then echo ${gSCOPE_DIR}/boot.config; \
	elif [ -f "${gCUSTOM_DIR}/boot.config" ]; \
	then echo ${gCUSTOM_DIR}/boot.config; \
	elif [ -f "${gHARDWARE_DIR}/boot.config" ]; \
	then echo ${gHARDWARE_DIR}/boot.config;\
	else echo ${gPLATFORM_DIR}/boot.config;\
	fi)
gpKERNEL_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/kernel.config" ]; \
	then echo ${gSCOPE_DIR}/kernel.config; \
	elif [ -f "${gCUSTOM_DIR}/kernel.config" ]; \
	then echo ${gCUSTOM_DIR}/kernel.config; \
	elif [ -f "${gHARDWARE_DIR}/kernel.config" ]; \
	then echo ${gHARDWARE_DIR}/kernel.config;\
	else echo ${gPLATFORM_DIR}/kernel.config;\
	fi)
gSKIN_MKFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/skin.mk" ]; \
	then echo ${gSCOPE_DIR}/skin.mk; \
	elif [ -f "${gCUSTOM_DIR}/skin.mk" ]; \
	then echo ${gCUSTOM_DIR}/skin.mk; \
	elif [ -f "${gHARDWARE_DIR}/skin.mk" ]; \
	then echo ${gHARDWARE_DIR}/skin.mk;\
	else echo ${gPLATFORM_DIR}/skin.mk;\
	fi)
gSDK_MKFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/sdk.mk" ]; \
	then echo ${gSCOPE_DIR}/sdk.mk; \
	elif [ -f "${gCUSTOM_DIR}/sdk.mk" ]; \
	then echo ${gCUSTOM_DIR}/sdk.mk; \
	elif [ -f "${gHARDWARE_DIR}/sdk.mk" ]; \
	then echo ${gHARDWARE_DIR}/sdk.mk;\
	else echo ${gPLATFORM_DIR}/sdk.mk;\
	fi)
export gSDK_CFGFILE gpBOOT_CFGFILE gpKERNEL_CFGFILE
export gSKIN_MKFILE gSDK_MKFILE
gpKERNEL_SDK_CFGFILE := ${gSDK_DIR}/target/linux/ramips/mt7621/config-3.10
export gpKERNEL_SDK_CFGFILE

# ********************************** #
# ******** platform macro ********** #
# ********************************** #
gpUPGRADE_IMAGE = ${gSDK_DIR}/bin/ramips-glibc/openwrt-ramips-mt7621-mt7621-squashfs-sysupgrade.bin
export gpUPGRADE_IMAGE
gBALE_MAKEFILE = ${gPLATFORM_DIR}/arch/Makefile.flash
export gBALE_MAKEFILE

# **************************************** #
# ********* compile environment ********** #
# **************************************** #
gARCH = mipsel
export gARCH
# webpage thems
gpWUI_ADMIN_THEME = ace
export gpWUI_ADMIN_THEME
# misc cross environment
gLIB_CFLAGS := -I${gINSTALL_DIR}/include
gLIB_LDFLAGS := -L${gINSTALL_DIR}/lib -levent
gCOM_CFLAGS := -I${gINSTALL_DIR}/include
gCOM_LDFLAGS := -L${gINSTALL_DIR}/lib -lland -levent
gEXE_CFLAGS := -I${gINSTALL_DIR}/include
gEXE_LDFLAGS := -L${gINSTALL_DIR}/lib -lland -ldl -levent
export gLIB_CFLAGS gLIB_LDFLAGS
export gCOM_CFLAGS gCOM_LDFLAGS
export gEXE_CFLAGS gEXE_LDFLAGS



