#!/bin/sh

cons="  0 0 662"
disk="  0 0 660"
null="  0 0 666"
urandom="  root root  644"
mkdev () 
{    # usage: mkdev name [bcu] major minor owner group mode
    if [ "$opt_v" ]
    then    
        if [ "$opt_d" ]
        then    
            echo "sudo rm -f $1"
        else
            echo "$1        = $2 $3 $4 $5:$6 $7"
        fi
    fi
    [ ! "$opt_n" ] && rm -f $1 &&
    [ ! "$opt_d" ] && mknod $1 $2 $3 $4 &&
    chown $5:$6 $1 &&
    chmod $7 $1
}

# mount proc/tmp filesystem
mount -t proc /proc /proc
mount -t sysfs /sys /sys
mount -n -t tmpfs tmpfs /tmp
# make /var
mkdir /tmp/var
chmod 0755 /tmp/var
mkdir /var/run
mkdir /var/lock
mkdir /var/log
# make /mnt
mkdir /tmp/mnt
chmod 0755 /tmp/mnt
# make /dev
mkdir /tmp/dev
chmod 0755 /tmp/dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

# make /etc
mkdir /tmp/etcbk
cp -R /etc/* /tmp/etcbk
mount -n -t tmpfs tmpfs /etc
chmod 0755 /etc
mv /tmp/etcbk/* /etc
rm -fr /tmp/etcbk
# make /lib/firmware can write at the no overlay system, some driver need write here(MT7603/MT7663)
if [ -d /lib/firmware ]; then
    if [ `ls -A /lib/firmware` != "" ]; then
        mkdir /tmp/firmwarebk
        cp -R /lib/firmware/* /tmp/firmwarebk
        mount -n -t tmpfs tmpfs /lib/firmware
        chmod 0755 /lib/firmware
        mv /tmp/firmwarebk/* /lib/firmware/
        rm -fr /tmp/firmwarebk
    fi
fi

# Serial
mkdev	dev/console c   5   1   $cons
mkdev	dev/ttyS0   c	4   64	$cons
mkdev	dev/ttyS1   c	4   65	$cons
mkdev	dev/ttyS2   c	4   66	$cons
mkdev   dev/ttyACM0  c   166 0   $disk
mkdev   dev/ttyACM1  c   166 1   $disk
mkdev   dev/ttyACM2  c   166 2   $disk
mkdev   dev/ttyACM3  c   166 3   $disk
mkdev   dev/ttyACM4  c   166 4   $disk
mkdev   dev/ttyACM5  c   166 5   $disk
mkdev	dev/ttyUSB0   c	188 0	$cons
mkdev	dev/ttyUSB1   c	188 1	$cons
mkdev	dev/ttyUSB2   c	188 2	$cons
mkdev	dev/ttyUSB3   c	188 3	$cons
mkdev	dev/ttyUSB4   c	188 4	$cons
mkdev	dev/ttyUSB5   c	188 5	$cons
mkdev	dev/ttyUSB6   c	188 6	$cons
#mkdev	dev/pts/0   c	136	0   $cons 
#mkdev	dev/pts/1   c	136	1   $cons 
#mkdev	dev/pts/2   c	136	2   $cons 
#mkdev	dev/pts/3   c	136	3   $cons 
#mkdev	dev/pts/4   c	136	4   $cons 
#mkdev	dev/pts/5   c	136	5   $cons 
mkdev	dev/ptyp0   c	2   0	$urandom
mkdev	dev/ptyp1   c	2   1	$urandom
mkdev	dev/ptyp2   c	2   2	$urandom
mkdev	dev/ptyp3   c	2   3	$urandom
mkdev	dev/ptyp4   c	2   4	$urandom
mkdev	dev/ptyp5   c	2   5	$urandom
mkdev	dev/ptyp6   c	2   6	$urandom
mkdev	dev/ttyp0   c	3   0	$urandom
mkdev	dev/ttyp1   c	3   1	$urandom
mkdev	dev/ttyp2   c	3   2	$urandom
mkdev	dev/ttyp3   c	3   3	$urandom
mkdev	dev/ttyp4   c	3   4	$urandom
mkdev	dev/ttyp5   c	3   5	$urandom
mkdev	dev/ttyp6   c	3   5	$urandom
mkdev	dev/ptmx    c	5   2	$null
# Memory
mkdev	dev/mem     c	1   1	$disk
mkdev	dev/ram0    b	1   0	$disk
mkdev	dev/ram1    b	1   1	$disk 
mkdev	dev/ram2    b	1   2	$disk
mkdev	dev/ram3    b	1   3	$disk
mkdev	dev/ram4    b	1   4	$disk
mkdev	dev/ram5    b	1   5	$disk
# Storage
mkdev   dev/mtdblock0 b  31 0 $disk
mkdev   dev/mtdblock1 b  31 1 $disk
mkdev   dev/mtdblock2 b  31 2 $disk
mkdev   dev/mtdblock3 b  31 3 $disk
mkdev   dev/mtdblock4 b  31 4 $disk
mkdev   dev/mtdblock5 b  31 5 $disk
mkdev   dev/mtdblock6 b  31 6 $disk
mkdev   dev/mtdblock7 b  31 7 $disk
mkdev   dev/mtd0      c  90 0 $disk
mkdev   dev/mtd0ro    c  90 1 $disk
mkdev   dev/mtd1      c  90 2 $disk
mkdev   dev/mtd1ro    c  90 3 $disk
mkdev   dev/mtd2      c  90 4 $disk
mkdev   dev/mtd2ro    c  90 5 $disk
mkdev   dev/mtd3      c  90 6 $disk
mkdev   dev/mtd3ro    c  90 7 $disk
mkdev   dev/mtd4      c  90 8 $disk
mkdev   dev/mtd4ro    c  90 9 $disk
mkdev   dev/mtd5      c  90 10 $disk
mkdev   dev/mtd5ro    c  90 11 $disk
mkdev   dev/mtd6      c  90 12 $disk
mkdev   dev/mtd6ro    c  90 13 $disk
mkdev   dev/mtd7      c  90 14 $disk
mkdev   dev/mtd7ro    c  90 15 $disk
mkdev   dev/mmcblk0    b  179 0 $disk
mkdev   dev/mmcblk0p1    b  179 1 $disk
mkdev   dev/mmcblk0p2    b  179 2 $disk
mkdev   dev/mmcblk0p3    b  179 3 $disk
mkdev   dev/mmcblk0p4    b  179 4 $disk
mkdev   dev/sda    b  8 0 $disk
mkdev   dev/sda1    b  8 1 $disk
mkdev   dev/sda2    b  8 2 $disk
mkdev   dev/sda3    b  8 3 $disk
mkdev   dev/sda4    b  8 4 $disk
# Network
mkdev   dev/cdc-wdm0    c  180 176 $cons
mkdev   dev/cdc-wdm1    c  180 177 $cons
mkdev   dev/cdc-wdm2    c  180 178 $cons
mkdev   dev/cdc-wdm3    c  180 179 $cons

# Misc
mkdev	dev/zero	c 1	5	$cons
mkdev	dev/ppp	    c	108	0   $cons
mkdev	dev/null    c	1   3	$null
mkdev	dev/random  c	1   8	$urandom
mkdev	dev/urandom c   1   9   $urandom
mkdev	dev/hwnat0  c	220	0   $cons
mkdev	dev/watchdog   c 10   130   $cons
mkdev	dev/watchdog9   c 10   129   $cons

# load the modules
/sbin/kmodloader

# sysctl
for CONF in /etc/sysctl.d/*.conf /etc/sysctl.conf; do
    [ -f "$CONF" ] && sysctl -e -p "$CONF" >&-
done

# Loopback interface
ifconfig lo 127.0.0.0 up
route add -net 127.0.0.0 netmask 255.255.255.0 dev lo

# init the raw syslog
ln -s /dev/log /var/syslogd
syslogd -L -O /var/bootup.syslog

# mdev
mdev -s

# run the land
. /etc/init.d/land;start


