# **************************************** #
# ******* Directory Definition *********** #
# **************************************** #
# bootloader
gpBOOT_DIR := ${gPLATFORM_DIR}/boot
export gpBOOT_DIR
# ftp pub server
gpFTP_PUB_URL := ftp://ftp.wmdevice.com
gpFTP_PUB_PASSWD := dl:tiger7@ASHYELF
gpFTP_PUB_SDK := ${gpFTP_PUB_URL}/pub/sdk/wrt
gpFTP_PUB_REPO := ${gpFTP_PUB_URL}/pub/sdk/wrt/${gHARDWARE}/${gCUSTOM}
gpFTP_PUB_DIR := $(shell \
	if [ "X${gSCOPE}" = "Xstd" ]; \
	then echo ${gpFTP_PUB_URL}/pub/${gCUSTOM}/; \
	else echo ${gpFTP_PUB_URL}/custom/${gCUSTOM}/; \
	fi)
export gpFTP_PUB_URL gpFTP_PUB_PASSWD gpFTP_PUB_SDK gpFTP_PUB_REPO gpFTP_PUB_DIR

# **************************************** #
# ********* configure file defined******** #
# **************************************** #
# SDK的配置文件位置
gSDK_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/sdk.config" ]; \
	then echo ${gSCOPE_DIR}/sdk.config; \
	elif [ -f "${gCUSTOM_DIR}/sdk.config" ]; \
	then echo ${gCUSTOM_DIR}/sdk.config; \
	elif [ -f "${gHARDWARE_DIR}/sdk.config" ]; \
	then echo ${gHARDWARE_DIR}/sdk.config;\
	else echo ${gPLATFORM_DIR}/sdk.config;\
	fi)
gpBOOT_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/boot.config" ]; \
	then echo ${gSCOPE_DIR}/boot.config; \
	elif [ -f "${gCUSTOM_DIR}/boot.config" ]; \
	then echo ${gCUSTOM_DIR}/boot.config; \
	elif [ -f "${gHARDWARE_DIR}/boot.config" ]; \
	then echo ${gHARDWARE_DIR}/boot.config;\
	else echo ${gPLATFORM_DIR}/boot.config;\
	fi)
gpKERNEL_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/kernel.config" ]; \
	then echo ${gSCOPE_DIR}/kernel.config; \
	elif [ -f "${gCUSTOM_DIR}/kernel.config" ]; \
	then echo ${gCUSTOM_DIR}/kernel.config; \
	elif [ -f "${gHARDWARE_DIR}/kernel.config" ]; \
	then echo ${gHARDWARE_DIR}/kernel.config;\
	else echo ${gPLATFORM_DIR}/kernel.config;\
	fi)
gSKIN_MKFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/skin.mk" ]; \
	then echo ${gSCOPE_DIR}/skin.mk; \
	elif [ -f "${gCUSTOM_DIR}/skin.mk" ]; \
	then echo ${gCUSTOM_DIR}/skin.mk; \
	elif [ -f "${gHARDWARE_DIR}/skin.mk" ]; \
	then echo ${gHARDWARE_DIR}/skin.mk;\
	else echo ${gPLATFORM_DIR}/skin.mk;\
	fi)
gSDK_MKFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/sdk.mk" ]; \
	then echo ${gSCOPE_DIR}/sdk.mk; \
	elif [ -f "${gCUSTOM_DIR}/sdk.mk" ]; \
	then echo ${gCUSTOM_DIR}/sdk.mk; \
	elif [ -f "${gHARDWARE_DIR}/sdk.mk" ]; \
	then echo ${gHARDWARE_DIR}/sdk.mk;\
	else echo ${gPLATFORM_DIR}/sdk.mk;\
	fi)
export gSDK_CFGFILE gpBOOT_CFGFILE gpKERNEL_CFGFILE
export gSKIN_MKFILE gSDK_MKFILE
gpKERNEL_SDK_CFGFILE := ${gSDK_DIR}/target/linux/ramips/mt76x8/config-5.10
export gpKERNEL_SDK_CFGFILE

# ********************************** #
# ******** platform macro ********** #
# ********************************** #
gpUPGRADE_IMAGE = ${gSDK_DIR}/bin/targets/ramips/mt76x8/openwrt-ramips-mt76x8-ashyelf_r600-squashfs-sysupgrade.bin
export gpUPGRADE_IMAGE
gBALE_MAKEFILE = ${gPLATFORM_DIR}/arch/Makefile.flash
export gBALE_MAKEFILE

# **************************************** #
# ********* compile environment ********** #
# **************************************** #
gARCH = mipsel
export gARCH
# webpage thems
gpWUI_ADMIN_THEME = ace
export gpWUI_ADMIN_THEME
# misc cross environment
gLIB_CFLAGS := -I${gINSTALL_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation -Wno-stringop-overflow
gLIB_LDFLAGS := -L${gINSTALL_DIR}/lib -levent
gCOM_CFLAGS := -I${gINSTALL_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation -Wno-stringop-overflow
gCOM_LDFLAGS := -L${gINSTALL_DIR}/lib -lland -levent
gEXE_CFLAGS := -I${gINSTALL_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation -Wno-stringop-overflow
gEXE_LDFLAGS := -L${gINSTALL_DIR}/lib -lland -ldl -levent
export gLIB_CFLAGS gLIB_LDFLAGS
export gCOM_CFLAGS gCOM_LDFLAGS
export gEXE_CFLAGS gEXE_LDFLAGS



