#!/bin/bash

###################################
############# D218 ################
###################################
make gBOARDID=smtk2-mt7628-d218-8m pid
make pidinfo
make clean
make distclean
make dep
make
make sz
make ftp
for tmp in h728 wlinker120 hx shfly hsta szrc
do
    make gBOARDID=smtk2-mt7628-d218-8m-${tmp} pid
    ./mkdel
    make dep
    make
    make sz
    make ftp
done

make gBOARDID=smtk2-mt7628-d218-std pid
make clean
make distclean
make dep
make
make sz
make ftp
make repo
for tmp in oled ipsec sr sx ok gs gg ggnw xyc lega tqstd inrico zwzx hmjtx base rover
do
    make gBOARDID=smtk2-mt7628-d218-${tmp} pid
    make pidinfo
    make clean
    make distclean
    make dep
    make
    make sz
    make ftp
done

