#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=96
STOP=3

start()
{
    # make /mnt
    mkdir /tmp/mnt
    chmod 0755 /tmp/mnt
    # make /etc
    mkdir /tmp/etcbk
    cp -R /etc/* /tmp/etcbk
    mount -n -t tmpfs tmpfs /etc
    chmod 0755 /etc
    mv /tmp/etcbk/* /etc
    rm -fr /tmp/etcbk
    # make /lib/firmware can write at the no overlay system, some driver need write here(MT7603/MT7663)
    if [ -d /lib/firmware ]; then
        if [ `ls -A /lib/firmware` != "" ]; then
            mkdir /tmp/firmwarebk
            cp -R /lib/firmware/* /tmp/firmwarebk
            mount -n -t tmpfs tmpfs /lib/firmware
            chmod 0755 /lib/firmware
            mv /tmp/firmwarebk/* /lib/firmware/
            rm -fr /tmp/firmwarebk
        fi
    fi

    # Loopback interface
    ifconfig lo 127.0.0.0 up
    route add -net 127.0.0.0 netmask 255.255.255.0 dev lo

    # init the raw syslog
    ln -s /dev/log /var/syslogd
    syslogd -L -O /var/bootup.syslog
}
stop()
{
    ifconfig lo down
}
